[project]
name = "rml_qrcode"
description = "QR code plugin for reportlab RML language"
version = "0.0.0"
authors = [
	{ name = "Miroslav Bendík", email = "miroslav.bendik@gmail.com" }
]
dependencies = [
	"qrcode",
	"z3c.rml",
	"six",
]

[project.optional-dependencies]
dev = [
	"tox",
	"pylint",
	"pre-commit",
	"bump2version"
]

[build-system]
requires = ["setuptools ~= 58.0"]
